#!/bin/bash

function download() {
    url=$1
    dest=$2

    response=$(curl -X GET ${url} -o -)
    format=$(echo ${response} | jq -r .format)
    if [ "${format}" = "base64" ] ; then
        echo ${response} | jq -j .content | base64 -d > $dest
    elif [ "${format}" = "text" ] ; then
        echo ${response} | jq -j .content > $dest
    else
        echo "Format ${format} of file ${dest} not supported"
        echo ${response} | jq -j .content > $dest
    fi
}

notebook_created="no"

function get_notebook() {
    ## Creates a new notebook if needed. Sets flag to delete if
    ## notebook was re-created.
    apiurl=$1
    sessionid=$2
    serviceid=$3
    svcinfo=`curl --silent -X GET "${apiurl}/${serviceid}" -H  "accept: application/json"`
    if [ $(echo ${svcinfo} | jq -j .sessionId) = "${sessionid}" ] ; then
        return ## NOTEBOOK_URL unchanged.
    fi
    
    svcinfo=`curl --silent -X POST "${apiurl}" -H  "accept: application/json" \
                  -H  "Content-Type: application/json" -d "{\"sessionId\":\"${sessionid}\"}"`
    notebook_created="yes"
    
    svcurl=`echo ${svcinfo} | jq -j .serviceURL`
    if [ "${svcurl}" = "null" ] ; then
        echo "Session ${sessionid} no longer exists. Cannot download data."
        exit 1
    fi

    SERVICE_ID=`echo ${svcinfo} | jq -j .id`
    echo "Wait for service ${SERVICE_ID} to be re-created at ${svcurl}."
    while ! curl --silent -IL -X GET ${svcurl} | grep "200 OK" ; do
        sleep 5
    done
    NOTEBOOK_URL=${svcurl}
}

function delete_notebook() {
    apiurl=$1
    if [ "${notebook_created}" = "yes" ] ; then
        curl -X DELETE "${apiurl}/${SERVICE_ID}" -H  "accept: */*"
    fi
}

function download_working_dir_data() {
    if [ ! -e download_filelist.dat ] ; then
        echo "Nothing to download from working dir."
        return
    fi
    apiurl=$1
    for file in `cat download_filelist.dat` ; do
        download ${apiurl}/${file} ${HOME}/${file}
    done
}

conda install -y -c conda-forge curl jq || exit 1


# =======================================================
# Everything below here is generated by the snapshot job:
# =======================================================
NOTEBOOK_URL=http://192.168.99.109/swirrl/jupyter/6b681e51-61b0-480d-b2ed-db8913f6f4e6
SERVICE_ID=6b681e51-61b0-480d-b2ed-db8913f6f4e6
get_notebook http://192.168.99.109/swirrl-api/v1.0/notebook b3c2933e-d7ad-4a12-8e98-e81ce859ef16 6b681e51-61b0-480d-b2ed-db8913f6f4e6
mkdir -p ~/data/staginghistory/stage.00003
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_201301-201312.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_201301-201312.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_190201-190212.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_190201-190212.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_199401-199412.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_199401-199412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_194701-194712.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_194701-194712.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_193001-193012.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_193001-193012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_195401-195412.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_195401-195412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_188101-188112.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_188101-188112.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_194601-194612.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_194601-194612.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_191701-191712.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_191701-191712.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_186701-186712.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_186701-186712.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_199601-199612.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_199601-199612.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_189801-189812.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_189801-189812.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_194501-194512.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_194501-194512.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_191401-191412.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_191401-191412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_185101-185112.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_185101-185112.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_186201-186212.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_186201-186212.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_191801-191812.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_191801-191812.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_187701-187712.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_187701-187712.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_192201-192212.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_192201-192212.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_192801-192812.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_192801-192812.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_193401-193412.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_193401-193412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_185501-185512.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_185501-185512.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_197801-197812.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_197801-197812.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_197001-197012.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_197001-197012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_196101-196112.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_196101-196112.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_188901-188912.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_188901-188912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_186901-186912.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_186901-186912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_198701-198712.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_198701-198712.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_185801-185812.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_185801-185812.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_185701-185712.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_185701-185712.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_190801-190812.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_190801-190812.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_187201-187212.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_187201-187212.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_195901-195912.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_195901-195912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_201001-201012.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_201001-201012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_191901-191912.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_191901-191912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_194901-194912.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_194901-194912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_197701-197712.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_197701-197712.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_191201-191212.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_191201-191212.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_197301-197312.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_197301-197312.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_199901-199912.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_199901-199912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_192101-192112.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_192101-192112.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_192001-192012.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_192001-192012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_187801-187812.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_187801-187812.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_193801-193812.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_193801-193812.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_186501-186512.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_186501-186512.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_194301-194312.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_194301-194312.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_190901-190912.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_190901-190912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_193601-193612.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_193601-193612.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_186101-186112.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_186101-186112.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_198201-198212.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_198201-198212.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_199201-199212.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_199201-199212.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_190001-190012.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_190001-190012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_197101-197112.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_197101-197112.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_198301-198312.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_198301-198312.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_196501-196512.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_196501-196512.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_188001-188012.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_188001-188012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_186401-186412.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_186401-186412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_abrupt-4xCO2_r1i1p1f1_gr_185001-185012.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_abrupt-4xCO2_r1i1p1f1_gr_185001-185012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_192601-192612.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_192601-192612.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_200001-200012.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_200001-200012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_201101-201112.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_201101-201112.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_200701-200712.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_200701-200712.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_194101-194112.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_194101-194112.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_197901-197912.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_197901-197912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_198101-198112.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_198101-198112.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_196801-196812.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_196801-196812.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_198001-198012.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_198001-198012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_187401-187412.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_187401-187412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_190301-190312.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_190301-190312.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_197501-197512.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_197501-197512.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_188701-188712.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_188701-188712.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_192501-192512.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_192501-192512.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_185401-185412.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_185401-185412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_195101-195112.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_195101-195112.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_192901-192912.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_192901-192912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_193201-193212.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_193201-193212.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_187501-187512.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_187501-187512.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_200501-200512.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_200501-200512.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_200601-200612.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_200601-200612.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_189401-189412.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_189401-189412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_185301-185312.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_185301-185312.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_195001-195012.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_195001-195012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_192401-192412.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_192401-192412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_189001-189012.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_189001-189012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_193501-193512.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_193501-193512.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_196001-196012.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_196001-196012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_191001-191012.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_191001-191012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_188401-188412.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_188401-188412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_193901-193912.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_193901-193912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_190701-190712.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_190701-190712.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_187601-187612.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_187601-187612.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_187101-187112.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_187101-187112.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_200901-200912.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_200901-200912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_192701-192712.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_192701-192712.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_198801-198812.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_198801-198812.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_199701-199712.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_199701-199712.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_200801-200812.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_200801-200812.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_196401-196412.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_196401-196412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_190401-190412.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_190401-190412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_198901-198912.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_198901-198912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_189901-189912.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_189901-189912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_188601-188612.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_188601-188612.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_187901-187912.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_187901-187912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_193101-193112.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_193101-193112.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_200101-200112.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_200101-200112.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_196601-196612.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_196601-196612.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_198401-198412.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_198401-198412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_195801-195812.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_195801-195812.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_186801-186812.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_186801-186812.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_195601-195612.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_195601-195612.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_188501-188512.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_188501-188512.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_200301-200312.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_200301-200312.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_185601-185612.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_185601-185612.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_191501-191512.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_191501-191512.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_186001-186012.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_186001-186012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_199501-199512.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_199501-199512.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_193701-193712.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_193701-193712.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_195201-195212.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_195201-195212.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_193301-193312.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_193301-193312.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/swirrl_fileinfo.json ~/data/staginghistory/stage.00003/swirrl_fileinfo.json
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_194401-194412.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_194401-194412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_199001-199012.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_199001-199012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_188801-188812.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_188801-188812.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_189701-189712.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_189701-189712.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_194201-194212.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_194201-194212.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_188301-188312.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_188301-188312.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_195501-195512.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_195501-195512.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_199301-199312.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_199301-199312.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_189101-189112.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_189101-189112.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_196201-196212.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_196201-196212.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_189501-189512.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_189501-189512.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_198601-198612.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_198601-198612.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_194801-194812.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_194801-194812.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_189601-189612.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_189601-189612.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_197601-197612.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_197601-197612.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_196701-196712.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_196701-196712.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_185901-185912.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_185901-185912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_185201-185212.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_185201-185212.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_187301-187312.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_187301-187312.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_199101-199112.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_199101-199112.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_190501-190512.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_190501-190512.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_200401-200412.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_200401-200412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_191601-191612.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_191601-191612.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_186301-186312.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_186301-186312.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_196301-196312.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_196301-196312.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_191301-191312.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_191301-191312.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_189301-189312.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_189301-189312.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_197201-197212.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_197201-197212.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_189201-189212.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_189201-189212.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_197401-197412.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_197401-197412.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_186601-186612.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_186601-186612.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_198501-198512.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_198501-198512.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_187001-187012.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_187001-187012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_190601-190612.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_190601-190612.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_195701-195712.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_195701-195712.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_196901-196912.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_196901-196912.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_192301-192312.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_192301-192312.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_190101-190112.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_190101-190112.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_191101-191112.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_191101-191112.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_195301-195312.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_195301-195312.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_188201-188212.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_188201-188212.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_194001-194012.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_194001-194012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_185001-185012.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_185001-185012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_201201-201212.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_201201-201212.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_199801-199812.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_199801-199812.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_200201-200212.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_200201-200212.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_201401-201412.nc ~/data/staginghistory/stage.00003/psl_Amon_EC-Earth3-AerChem_hist-piNTCF_r1i1p1f1_gr_201401-201412.nc
mkdir -p ~/data/staginghistory/stage.00002
ln ~/data/staginghistory/stage.00003//psl_Amon_EC-Earth3-AerChem_abrupt-4xCO2_r1i1p1f1_gr_185001-185012.nc ~/data/staginghistory/stage.00002/psl_Amon_EC-Earth3-AerChem_abrupt-4xCO2_r1i1p1f1_gr_185001-185012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00002/swirrl_fileinfo.json ~/data/staginghistory/stage.00002/swirrl_fileinfo.json
mkdir -p ~/data/staginghistory/stage.00001
ln ~/data/staginghistory/stage.00002//psl_Amon_EC-Earth3-AerChem_abrupt-4xCO2_r1i1p1f1_gr_185001-185012.nc ~/data/staginghistory/stage.00001/psl_Amon_EC-Earth3-AerChem_abrupt-4xCO2_r1i1p1f1_gr_185001-185012.nc
download ${NOTEBOOK_URL}/api/contents/data/staginghistory/stage.00001/swirrl_fileinfo.json ~/data/staginghistory/stage.00001/swirrl_fileinfo.json
ln -s ~/data/staginghistory/stage.00003 ~/data/latest
download_working_dir_data ${NOTEBOOK_URL}/api/contents
delete_notebook http://192.168.99.109/swirrl-api/v1.0/notebook
